name: BuildAndRunTests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - src/**
  pull_request:
    branches: [ "main" ]
    paths:
    - src/**
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout CShell
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CShell.sln 

    - name: Build
      run: dotnet build --no-restore CShell.sln --property WarningLevel=0
      
    - name: Test
      run: dotnet test --no-build --verbosity normal CShell.sln
